version: '3.3'
services:
  mongo:
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
    image: mongo
    ports:
      - '27016:27017'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jsonschemaextraction
    ports:
      - '4200:4200'
    environment:
      - MONGODB_URI=mongodb://$MONGO_INITDB_ROOT_USERNAME:$MONGO_INITDB_ROOT_PASSWORD@mongodb:$MONGO_PORT/jsonschemadiscovery?authSource=admin
      - SECRET_TOKEN=$SECRET_TOKEN